### ISSUE TITLE
Nxus 4 Approach

### ISSUE THREAD

**Issue by mjreich** [nxus/admin#2]
@loppear writing this up to gut check approach with regards to re-use of nxus-web.
## Features
- Re-usable CRUD for managing data/configuration restricted to 'admin' users
- Admin theme for rendering pages
- Admin menu for navigating admin pages
- Extendable by modules
## Approach
- Admin module provides an API for one-line instantiation as well as an extendable class (these may again be the same behind the scenes)

``` javascript
admin.manage('my-model')

class MyModelAdmin extends AdminMVCModule {
  // Expects the same controller/templates structure as MVCModule
}
```
- We will still need adminPage/adminRoute to support arbitrary actions separate from model CRUD

``` javascript
admin.page('My Page', '/my-page', ::this._adminPage)

admin.route('/my-route', ::this._adminRoute)
```
## Questions
- Did class/instance actions make it into web or need to be integrated?
- Is there a theme option on MVCModule/Controller to define this?
- Do we need to reimplement MVCModule and Controller to handle admin, or just MVCModule?
- If we override it, do we expect the same model paths?  Seems like if we have ListView and AdminView modules together, one of them needs to not 'own' the model

**Comment by mjreich** [comment]
Proposing a couple of API changes:

1. Combine route/page:

```javascript
//default partial version, wrapped in admin theme. Title is implicitly extracted from the last route segment using morph.
admin.page('/my-page', 'my-template-partial') 

//Specify opts, like title, menu.
admin.page('/my-page', {title: 'My Page Title', label: 'Menu Label}, 'my-template-partial') 

//default handler version. If the return is a promise or a string, then the return is resolved rendered in the admin theme
admin.page('/my-page', () => {
  return template.render('my-template', opts)
})

//route version.  Next has to be explicitly called, or the res handled inside the handler.
admin.page('/my-route', {method: 'post'}, (req, res, next) => {
  //do something  
  res.redirect('/admin')
})
```

**Comment by loppear** [comment]
1. Approach: I expect `AdminController` to extend `EditController`, not `MVCModule` - these are model-specific.
  1. There might be a case for an AdminMVCModule as an alternative to `admin.page()`, but it feels like a mismatch still.
  1. Expect the same options object to be accepted by `admin.manage()` and `new AdminController` - upgrade to a class for custom model route handlers etc is just to move that options object to the constructor super() call.
  1. AdminController should mostly just need to set the `routePrefix` and `templatePrefix` and permissions-protected routes.
1. Question responses:
  1. Class/instance actions are still to-do, still make sense for View/EditController to me.
  1. Not sure what theme support specifically is needed?
  1. N/A
  1. AdminController will have different routes (prefixed by adminBasePath as today), it's intended that you can have multiple View/Edit/AdminController subclasses for the same model.
1. Routes & Pages - overall those changes look fine. I'm not sure about the handler version wrapping with the admin-template, and presumably that handler gets res/req?
